name: example
description: Example for flutter_networking package with GraphQL file upload

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network:
    path: ../
  file_picker: ^6.1.1
  path: ^1.8.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
