name: network
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  dio: ^5.0.0
  logger: ^2.2.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
