name: network
description: A starting point for Dart libraries or applications.
version: 0.2.0
publish_to: none
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  dio: ^5.8.0+1
  logger: ^2.3.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
